SELECT
    e.EMP_ID, e.F_NAME, e.L_NAME,
    h.START_DATE,
    d.DEP_NAME,
    j.JOB_TITLE,
	e.SALARY,
    CASE
        WHEN e.SALARY < j.MIN_SALARY THEN '* BELOW RANGE'
        WHEN e.SALARY > j.MAX_SALARY THEN '* ABOVE RANGE'
        WHEN e.SALARY = j.MAX_SALARY THEN 'CAPPED'
        ELSE ''
    END AS Salary_Flag    
FROM EMPLOYEES AS e

LEFT JOIN DEPARTMENTS d
    ON e.DEP_ID = d.DEPT_ID_DEP
LEFT JOIN JOBS j
	ON e.JOB_ID = j.JOB_IDENT
LEFT JOIN LOCATIONS l
	ON d.LOC_ID = l.LOCT_ID
LEFT JOIN JOB_HISTORY h
	ON e.EMP_ID = h.EMPL_ID
ORDER BY d.DEP_NAME, e.SALARY DESC
;
